[package]
name = "cndk8"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["telegram", "handlers"]
exclude = ["lab/", "duplicate_detection"]

[dependencies]
scraper = "0.16.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
