[package]
name = "cndk8"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["duplicate_detection"]
exclude = ["lab/"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
duplicate_detection = { path = "./duplicate_detection" }
