name: Rust Workflow

stages:
  - build
  - publish

.parallel:   
  parallel:
    matrix:
      - BUILD_TARGET [release, debug, publish]:

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    .extends: .parallel
    .stage: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --${BUILD_TARGET}
    - name: Run tests
      run: cargo test --${BUILD_TARGET}
    - name: Upload Telegram Bot
      uses: actions/upload-artifact@v4
      with:
        name: cndk8-telegram-bot
        path: target/release/telegram
    - name: Upload hello app
      uses: actions/upload-artifact@v4
      with:
        name: cndk8-hello
        path: target/release/cndk8

  ### copilot helped here, lets see how many commits it takes to make it work:
  publish: 
    if: github.ref == 'refs/heads/main' 
    # if: github.ref == 'refs/heads/main' && secrets.X_TOKEN != ''
    environment: publishing
    needs: build
    extends: .publish
    stage: publish
    runs-on: ubuntu-latest
    steps:
    - name: Set token environment variable
      run: echo "X_TOKEN=${{ secrets.X_TOKEN }}" >> $GITHUB_ENV
    - name: Display structure of downloaded files
      run: ls -lahR && pwd
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: cndk8-hello
        path: ./cndk8
    - name: Download telegram 
      uses: actions/download-artifact@v4
      with:
        name: cndk8-telegram-bot
        path: ./cndk8

    - name: display files after download
      run: ls -lahR && pwd
    - name: Publish to GitHub Packages
      run: |
        curl -u "${{ github.actor }}:${{ secrets.GH_TOKEN }}" \
          -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/assets?name=cndk8-hello.tar.gz" \
          --header "Content-Type: application/gzip" \
          --data-binary @./binary/cndk8-hello

## stage -> build app -> build containers -> deploy
