name: Rust Workflow

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Telegram Bot
      uses: actions/upload-artifact@v2
      with:
        name: cndk8-telegram-bot
        path: target/release/telegram
    - name: Upload hello app
      uses: actions/upload-artifact@v2
      with:
        name: cndk8-hello
        path: target/release/cndk8

  ### copilot helped here, lets see how many commits it takes to make it work:
  publish:
    if: github.ref == 'refs/heads/main' 
    # if: github.ref == 'refs/heads/main' && secrets.X_TOKEN != ''
    environment: publishing
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set token environment variable
      run: echo "X_TOKEN=${{ secrets.X_TOKEN }}" >> $GITHUB_ENV
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: cndk8-telegram-bot 
        path: ./telegram

    - name: Publish to GitHub Packages
      run: |
        curl -u "${{ github.actor }}:${{ secrets.GH_TOKEN }}" \
          -X POST "https://uploads.github.com/repos/${{ github.repository }}/releases/assets?name=cndk8.tar.gz" \
          --header "Content-Type: application/gzip" \
          --data-binary @./binary/cndk8-hello

## stage -> build app -> build containers -> deploy
